### ISSUE TITLE
圈子看动态仅有图像， 如果能有视频就更好了QAQ

### ISSUE THREAD

**Issue by YuQi9797** [happycao/lingxi-android#3]

**Comment by happycao** [comment]
视频好做，但是带宽太小，上传和播放压力太大了，图片都是经过压缩的，加载起来也很慢

**Comment by YuQi9797** [comment]
> 视频好做，但是带宽太小，上传和播放压力太大了，图片都是经过压缩的，加载起来也很慢

这个如果去用第三方库，加入进来会不会好一点？ 还是说自己来写呢？

**Comment by happycao** [comment]
> > 视频好做，但是带宽太小，上传和播放压力太大了，图片都是经过压缩的，加载起来也很慢
> 
> 这个如果去用第三方库，加入进来会不会好一点？ 还是说自己来写呢？

肯定是用第三方库，自己写太麻烦，需要一个类微信的小视频压缩算法，带宽问题是局限于我这服务器的，如果有资金使用云存储或其他资源服务器，将不是问题，和图片大同小异，无非是加载一个播放器就好了

**Comment by YuQi9797** [comment]
> > > 视频好做，但是带宽太小，上传和播放压力太大了，图片都是经过压缩的，加载起来也很慢
> > 
> > 
> > 这个如果去用第三方库，加入进来会不会好一点？ 还是说自己来写呢？
> 
> 肯定是用第三方库，自己写太麻烦，需要一个类微信的小视频压缩算法，带宽问题是局限于我这服务器的，如果有资金使用云存储或其他资源服务器，将不是问题，和图片大同小异，无非是加载一个播放器就好了

奥奥奥，谢谢解答！
